matrix:
    include:
        - language: cpp
          os: osx
          install:
              - cd src/omega/
              - python3 -m venv venv && . venv/bin/activate
              - pip install -r requirements.txt

              - conan remote add public-conan https://api.bintray.com/conan/bincrafters/public-conan 
              - conan profile new default --detect
              - conan profile update settings.compiler=apple-clang default
              - conan profile update settings.compiler.version=9.1 default
              - conan profile update settings.compiler.libcxx=libc++ default
              - cd build && conan install .. && cd ..
              -
              - cmake -G "Unix Makefiles" .
              - make omega-tests

          script: ../bin/omega-test
