render_delay: 0

materials:
    -
        name: Red
        color: 0

    -
        name: Yellow
        color: 1

    -
        name: Green
        color: 2

    -
        name: Cyan
        color: 3

scene:
    width: 320
    height: 240
    title: Omega
    background: blue
    edges: true

    objects:
        -
            name: Sphere 1
            type: sphere
            material: Cyan
            center: [-1, 1.5, -4]
            radius: 1

        -
            name: Triangle 1
            type: triangle
            material: Red
            rotation:
                type: 0
                angle: 1
                axis: [0, 0, 1]
            points:
                - [-1, -1, -3]
                - [1, -1, -3]
                - [0, 1, -3]

        -
            name: Triangle 2
            type: triangle
            material: Yellow
            rotation:
                type: 0
                angle: 1
                axis: [0, 0, 1]
            points:
                - [1, -1, -3]
                - [0, -1, -2]
                - [0, 1, -3]

        -
            name: Triangle 3
            type: triangle
            material: Green
            rotation:
                type: 0
                angle: 1
                axis: [0, 0, 1]
            points:
                - [-1, -1, -3]
                - [0, -1, -2]
                - [0, 1, -3]