scene:
    width: 650
    height: 480
    title: Omega
    background: blue
    objects:
        -
            name: Sphere 1
            type: sphere
            material: metal
            center: [1, 2, 3]
            radius: 12

        -
            name: Something
            type: mech
            material: metal
            points:
                - [1, 2, 3]
                - [2, 3, 4]
