scene:
    width: 640
    height: 480
    title: Omega
    background: blue
    objects:
        -
            name: Triangle 1
            type: triangle
            material: metal
            points:
                - [-1, -1, -2]
                - [1, -1, -2]
                - [0, 1, -2]
