materials:
    -
        name: Red
        color: 0

    -
        name: Yellow
        color: 1

    -
        name: Green
        color: 2

scene:
    width: 320
    height: 240
    title: Omega
    background: blue
    edges: true

    objects:
#        -
#            name: Sphere 1
#            type: sphere
#            material: Green
#            center: [2, 2, -4]
#            radius: 1
        -
            name: Triangle 1
            type: triangle
            material: Red
            points:
                - [-1, -1, -3]
                - [1, -1, -3]
                - [0, 1, -3]
        -
            name: Triangle 2
            type: triangle
            material: Yellow
            points:
                - [1, -1, -3]
                - [0, -1, -2]
                - [0, 1, -3]
        -
            name: Triangle 3
            type: triangle
            material: Green
            points:
                - [-1, -1, -3]
                - [0, -1, -2]
                - [0, 1, -3]